name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Activation du Bureau à distance
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    # Création des utilisateurs locaux
    - name: Create Local Users
      run: |
        # Utilisateur 1
        New-LocalUser "adamch23" -Password (ConvertTo-SecureString -AsPlainText "NewP@ssw0rd!" -Force) -FullName "Adam Ch23" -Description "CI User"
        Add-LocalGroupMember -Group "Administrators" -Member "adamch23"
        
        # Utilisateur 2
        New-LocalUser "janedoe" -Password (ConvertTo-SecureString -AsPlainText "AnotherP@ssw0rd!" -Force) -FullName "Jane Doe" -Description "CI User 2"
        Add-LocalGroupMember -Group "Administrators" -Member "janedoe"
        
        # Utilisateur 3
        New-LocalUser "bobsmith" -Password (ConvertTo-SecureString -AsPlainText "SecureP@ss1!" -Force) -FullName "Bob Smith" -Description "CI User 3"
        Add-LocalGroupMember -Group "Administrators" -Member "bobsmith"
        
        # Utilisateur 4
        New-LocalUser "sarajones" -Password (ConvertTo-SecureString -AsPlainText "MyP@ssw0rd2!" -Force) -FullName "Sara Jones" -Description "CI User 4"
        Add-LocalGroupMember -Group "Administrators" -Member "sarajones"

    # Installation et configuration d'OpenSSH (si nécessaire)
    - name: Install OpenSSH
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Start-Service sshd
        Set-Service -Name sshd -StartupType 'Automatic'

    # Création d'un tunnel avec Serveo
    - name: Create Tunnel with Serveo
      run: |
        ssh -o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net